### ISSUE TITLE
Suggestion to show approximate number of users and how old a instance is on https://searx.space/

### ISSUE THREAD

**Issue by solisinvictum** [searxng/searxng#1176]
Hey Folks,

using searxng is great. But it's even better if you knew approximately how many users an instance has.

Because from a privacy perspective, it's not the best thing to host searxng yourself and be the only user. Because that would bypass all the "protections" of searxng, because Google etc can still then create a profile that is then tailored to the single user.

So the best would be to use a public instance that has as many possible users as possible. However, finding that out at the moment is next to impossible. At the moment, the only way to find out is to search the Internet for Searxng instances and see how many would use them. 

It would also make sense to show how "old" an instance is. An instance that is older and has a "stable user base" could be more trustworthy in terms of stability and runtime than one that is only 3 days old and disappears on the fourth day.

However, the last suggestion is debatable. 

Translated with www.DeepL.com/Translator (free version)

**Comment by return42** [comment]
A SearXNG instance should never collect and/or offer any information about its user base.

> So the best would be to use a public instance that has as many possible users as possible

This is not the only criteria, from a privacy aspect a image proxy weights more .. the instance should not be hosted on Reverse-Proxies like Cloudflare .. the instance should not include any analytics libraries ..

We have a *ranking* discussion at https://github.com/searxng/searx-space/issues/99 and privacy is addressed in https://github.com/searxng/searx-space/issues/97

**Comment by catfluoride** [comment]
I know this issue is closed, and I agree that instances should not collect any kind of information about user base. But... What about publicly displaying just the number of queries over a given timeframe, without collecting any additional info?

Something on the likes of https://duckduckgo.com/traffic ?

**Comment by mrpaulblack** [comment]
I think something like this should be up to the instance maintainers; they can use a stack like prometheus and grafana for that for example IMO...

**Comment by solisinvictum** [comment]
If you want it to do right, for that even extra software isnt needed.

Nearly all Hosters let you show how much traffic your Server/Service/what_ever have made since start. That Info is already enough for the most "interested user" who wants to know how many Users this Instance have aprox~.

For me, still dont found a instance wich to use, because i dont found  any information about them. Still waiting for few answers for questions i asked over email.

**Comment by unixfox** [comment]
Showing how old the instance is, might be a good idea and is somewhat easy to add. We would need to add that info for every existing instance but that's doable and doesn't hurt the privacy.
The issue is that just because the instance is old, like 4 years old, doesn't mean it's a good instance. On https://searx.space you can find dozens of old instances that are outdated. (You can't actually know when looking at the version because searx has been on version 1.0 for a very long time)

**Comment by return42** [comment]
A instance should be updated regularly .. otherwise it will degrade over the time .. that is why I think not the "uptime" (of a URL) stands for quality .. that last update is shown in the footer:

![grafik](https://user-images.githubusercontent.com/554536/172041790-47656b22-9168-46d5-9def-e83de1a3551a.png)


BTW: I don't think we should do any ranking nor other implicit recommendations (at searx.space) .. the criteria for a recommendation are always individual from the user's point of view.  The criteria we currently have on searx.space are partly very technical and have no relevance for 90% of the users (the SSL version and how it is ranked e.g.).  Performance criteria can be distorted by caches.  Whatever criteria we choose, they are bypassable or do not fit the user's needs.
