### ISSUE TITLE
Brave didn't find any results.

### ISSUE THREAD

**Issue by julianfairfax** [searxng/searxng#1239]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**

2022.05.24-fddbc5ed

**How did you install SearXNG?**

I installed SearXNG using the official wiki

**What happened?**

I attempted to perform a search using the Brave engine, only to be faced with this error:
"Sorry! we didn't find any results. Please use another query or search in more categories."

**How To Reproduce**

Perform a search using the Brave engine

**Expected behavior**

Results should be displayed in place of an error

**Screenshots & Logs**

![image](https://user-images.githubusercontent.com/43753131/170507567-66ed9b51-fcdb-4861-9518-d405ae5c463d.png)

```
INFO    searx                         : load the default settings from /home/julian/Code/searxng/searx/settings.yml
INFO    searx                         : max_request_timeout=None
INFO    searx                         : version: 2022.05.24-fddbc5ed
INFO    searx.shared                  : Use shared_simple implementation
DEBUG   searx.webapp                  : static directory is /home/julian/Code/searxng/searx/static
DEBUG   searx.webapp                  : templates directory is /home/julian/Code/searxng/searx/templates
DEBUG   searx.webapp                  : starting webserver on 127.0.0.1:8888
 * Serving Flask app 'webapp' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
INFO    werkzeug                      :  * Running on http://127.0.0.1:8888 (Press CTRL+C to quit)
INFO    werkzeug                      :  * Restarting with stat
INFO    searx                         : load the default settings from /home/julian/Code/searxng/searx/settings.yml
INFO    searx                         : max_request_timeout=None
INFO    searx                         : version: 2022.05.24-fddbc5ed
INFO    searx.shared                  : Use shared_simple implementation
DEBUG   searx.webapp                  : static directory is /home/julian/Code/searxng/searx/static
DEBUG   searx.webapp                  : templates directory is /home/julian/Code/searxng/searx/templates
DEBUG   searx.plugins                 : searx.plugins.ahmia_filter: loaded
DEBUG   searx.plugins                 : searx.plugins.hash_plugin: loaded
DEBUG   searx.plugins                 : searx.plugins.hostname_replace: loaded
DEBUG   searx.plugins                 : searx.plugins.limiter: loaded
DEBUG   searx.plugins                 : searx.plugins.oa_doi_rewrite: loaded
DEBUG   searx.plugins                 : searx.plugins.search_on_category_select: loaded
DEBUG   searx.plugins                 : searx.plugins.self_info: loaded
DEBUG   searx.plugins                 : searx.plugins.tracker_url_remover: loaded
DEBUG   searx.plugins                 : searx.plugins.vim_hotkeys: loaded
DEBUG   searx.engines.dailymotion     : Initialized
INFO    searx                         : Send SIGUSR1 signal to pid 638984 to start the checker
INFO    searx                         : debug mode: checker is disabled
DEBUG   searx.webapp                  : starting webserver on 127.0.0.1:8888
WARNING werkzeug                      :  * Debugger is active!
INFO    werkzeug                      :  * Debugger PIN: 132-910-027
DEBUG   searx.network.wikidata        : HTTP Request: GET https://query.wikidata.org/sparql?query=%0ASELECT+%3Fitem+%3Fname%0AWHERE+%7B%0A++++%7B%0A++++++SELECT+%3Fitem%0A++++++WHERE+%7B+%3Fitem+wdt%3AP279%2A+wd%3AQ12132+%7D%0A++++%7D+UNION+%7B%0A++++++VALUES+%3Fitem+%7B+wd%3AP571+wd%3AP576+wd%3AP580+wd%3AP582+wd%3AP569+wd%3AP570+wd%3AP619+wd%3AP620+wd%3AP27+wd%3AP495+wd%3AP17+wd%3AP159+wd%3AP36+wd%3AP35+wd%3AP6+wd%3AP122+wd%3AP37+wd%3AP1082+wd%3AP2046+wd%3AP281+wd%3AP38+wd%3AP2048+wd%3AP400+wd%3AP50+wd%3AP170+wd%3AP57+wd%3AP175+wd%3AP178+wd%3AP162+wd%3AP176+wd%3AP58+wd%3AP272+wd%3AP264+wd%3AP123+wd%3AP449+wd%3AP750+wd%3AP86+wd%3AP577+wd%3AP136+wd%3AP364+wd%3AP212+wd%3AP957+wd%3AP275+wd%3AP277+wd%3AP348+wd%3AP840+wd%3AP1098+wd%3AP282+wd%3AP1018+wd%3AP218+wd%3AP169+wd%3AP112+wd%3AP1454+wd%3AP137+wd%3AP1029+wd%3AP225+wd%3AP274+wd%3AP1346+wd%3AP1120+wd%3AP498+wd%3AP856+wd%3AP1324+wd%3AP1581+%7D%0A++++%7D%0A++++OPTIONAL+%7B+%3Fitem+rdfs%3Alabel+%3Fname.+%7D%0A%7D%0A "HTTP/2 200 OK" (application/sparql-results+json;charset=utf-8)
DEBUG   searx.network.z-library       : HTTP Request: GET https://z-lib.org "HTTP/2 200 OK" (text/html; charset=UTF-8)
DEBUG   searx.engines.z-library       : using base_url: https:https://1lib.ch
DEBUG   searx.engines.z-library       : Initialized
DEBUG   searx.network.soundcloud      : HTTP Request: GET https://soundcloud.com "HTTP/2 200 OK" (text/html)
DEBUG   searx.engines.wikidata        : request time 0:00:00.205000
DEBUG   searx.engines.wikidata        : Initialized
DEBUG   searx.network.soundcloud      : HTTP Request: GET https://a-v2.sndcdn.com/assets/49-52723568.js "HTTP/2 200 OK" (application/javascript)
DEBUG   searx.engines.soundcloud      : Initialized
DEBUG   searx.network.wolframalpha    : HTTP Request: GET https://www.wolframalpha.com/input/api/v1/code?ts=9999999999999999999 "HTTP/1.1 200 OK"
DEBUG   charset_normalizer            : Encoding detection: ascii is most likely the one.
DEBUG   searx.engines.wolframalpha    : Initialized
Gtk-Message: 16:21:57.669: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:21:57.669: Failed to load module "canberra-gtk-module"
DEBUG   searx.webapp                  : http%3A//127.0.0.1%3A8888/ uses locale `en`
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:21:57] "GET / HTTP/1.1" 200 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:21:57] "GET /static/themes/simple/img/searxng.png HTTP/1.1" 304 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:21:57] "GET /static/themes/simple/css/searxng.min.css HTTP/1.1" 304 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:21:57] "GET /static/themes/simple/js/searxng.head.min.js HTTP/1.1" 304 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:21:57] "GET /static/themes/simple/js/searxng.min.js HTTP/1.1" 304 -
DEBUG   searx.search                  : actual_timeout=3.0 (default_timeout=3.0, ?timeout_limit=None, max_request_timeout=None)
DEBUG   searx.network.brave           : HTTP Request: GET https://search.brave.com/search?q=test&offset=0&spellcheck=1 "HTTP/2 200 OK" (text/html; charset=utf-8)
DEBUG   searx.engines.brave           : found 0 results
DEBUG   searx.webapp                  : http%3A//127.0.0.1%3A8888/search uses locale `en`
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:22:00] "POST /search HTTP/1.1" 200 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:22:00] "GET /static/themes/simple/css/searxng.min.css HTTP/1.1" 304 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:22:00] "GET /static/themes/simple/js/searxng.min.js HTTP/1.1" 304 -
INFO    werkzeug                      : 127.0.0.1 - - [26/May/2022 16:22:00] "GET /static/themes/simple/js/searxng.head.min.js HTTP/1.1" 304 -
```

**Additional context**

This issue also appears on the https://searx.namejeff.xyz/ and https://paulgo.io instances. I have not tried any others.

**Comment by mrpaulblack** [comment]
FYI there is already a PR for that: https://github.com/searxng/searxng/pull/1224

**Comment by julianfairfax** [comment]
> FYI there is already a PR for that: #1224

I see that. I tested it and it works perfectly so I've left a comment there saying it should be merged. I'll keep this open until that happens.

**Comment by julianfairfax** [comment]
Despite that PR having fixed the issue for me in my local instance, it seems any public instance I try still has the issue. This needs more work apparently.

**Comment by return42** [comment]
>  it seems any public instance I try still has the issue. This needs more work apparently.

This needs an update of the instance by the maintainer of the instance you tested.

We can't force maintainer to regularly update their instances.

**Comment by tiekoetter** [comment]
@return42 This is not the only problem.

Brave Search wants some cookies to be set if they blacklist an IP.

**Comment by return42** [comment]
@tiekoetter thanks for pointing out (seems similar to *CAPTCHA* issues) .. but then I think, we should open a new issue describing the problem .. "Brave simply doesn't work" is not qualifying the problem and the initial problem of this issue (no results) is solved.

**Comment by julianfairfax** [comment]
> >  it seems any public instance I try still has the issue. This needs more work apparently.
> 
> This needs an update of the instance by the maintainer of the instance you tested.
> 
> We can't force maintainer to regularly update their instances.

All of the ones I tried were updated. Sorry for not specifying that.

**Comment by julianfairfax** [comment]
@return42 this should be reopened. Brave still doesn't work on public instances.

**Comment by dalf** [comment]
Brave works on my local instance. I guess this is antibot problem.

**Comment by return42** [comment]
>> this should be reopened. Brave still doesn't work on public instances.

> Brave works on my local instance. I guess this is antibot problem.

I reopen this issue --> seems all public brave engines are blocked.

**Comment by return42** [comment]
Closed by

- https://github.com/searxng/searxng/pull/1729
