### ISSUE TITLE
Bug: duckduckgo engine

### ISSUE THREAD

**Issue by HerbCSO** [searxng/searxng#2146]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
Repository: https://github.com/searxng/searxng
Branch: master
Version: 2023.1.29+9d102fb0

**How did you install SearXNG?**
Running docker image searxng/searxng, image ID 5cac8b4bbf70
**What happened?**
DDG still returns `Error! Engines cannot retrieve results: duckduckgo ( Suspended: access denied )` even though the fix from #2081 is definitely applied (I checked by running `docker exec -it searxng_searxng_1 sh` and then in the container:

```
/usr/local/searxng # cat searx/engines/duckduckgo.py | grep Referer
    params['headers']['Referer'] = 'https://lite.duckduckgo.com/'
```

**How To Reproduce**
Run a search with DDG enabled

**Expected behavior**
No error returned by DDG engine

**Screenshots & Logs**

**Additional context**

**Technical report**

Error
  * Error: searx.exceptions.SearxEngineAccessDeniedException
  * Percentage: 5
  * Parameters: `('HTTP error 403',)`
  * File name: `searx/search/processors/online.py:113`
  * Function: `_send_http_request`
  * Code: `response = req(params['url'], **request_args)`

**Comment by chenghui-lee** [comment]
I'm having the exact setup with OP (docker, searxng version `2023.1.29+9d102fb0`), can confirm having the same issue.
![image](https://user-images.githubusercontent.com/57316431/215793622-37d2db0c-4f0a-4bab-ab99-8edaba3adf9f.png)

**Comment by dannykorpan** [comment]
Same error as @chenghui-lee with docker and same searxng version.

**Comment by rudism** [comment]
I noticed this again too and played around with adding request headers to see what they might be detecting this time, but couldn't find anything obvious. I can't even reproduce the 401/denied response outside of the searxng request... doing a straight `curl` of the request that searxng sends with identical headers and payload comes back with a 200. Maybe they're detecting based on some quirk in the way that the python library is building the request.

**Comment by ghost** [comment]
I'm having this same issue as well.

**Comment by Error00101** [comment]
Same setup, having the same issue.
Up until now it was possible to mitigate this with pulling a new docker image. 
- Just pulled the newest image: Still not working

**Comment by rasculatul** [comment]
Confirmed with the latest version 2023.1.27+6b71721c. Perhaps it's just me, however, I have noticed that duckduckgo consistently ends up with this error in SearXNG in the last months. Despite the recommendation to update to the latest version, it keeps coming back.

**Comment by rudism** [comment]
I believe DDG is actively working to prevent 3rd parties from scraping results, so it will be a cat-and-mouse game even if it gets fixed again this time.

**Comment by Bandit** [comment]
Same error for me

**Comment by danktankk** [comment]
same error and already updated to latest as of two minutes ago

**Comment by danktankk** [comment]
> 

I agree and believe that they are trying to push back...

**Comment by danktankk** [comment]
> I believe DDG is actively working to prevent 3rd parties from scraping results, so it will be a cat-and-mouse game even if it gets fixed again this time.

I agree with this and do believe that they are trying to push back a little...  I also have this issue regardless of being up to date.

**Comment by AlyoshaVasilieva** [comment]
>I believe DDG is actively working to prevent 3rd parties from scraping results

I don't think this is unique to DDG, search engines generally don't want anyone scraping them.

**Comment by nicfab** [comment]
Same error for me.

![sshot_2023-02-01_13 32 41](https://user-images.githubusercontent.com/24752671/216043655-12d0fad2-a2a5-41d6-8637-435c213150ac.png)

**Comment by ChronosXYZ** [comment]
I confirm this issue on the latest docker image version of SearXNG.

**Comment by Bandit** [comment]
My Google is also blocked now for "suspicious usage"

**Comment by Waldorf3** [comment]
I get the same error, but

> > I believe DDG is actively working to prevent 3rd parties from scraping results
> 
> I don't think this is unique to DDG, search engines generally don't want anyone scraping them.

DDG is itself an aggregater, a meta search engine getting it's result from other search engines. What is even the point in including it in something like searx. Why not just stick with the primary souces?

**Comment by Error00101** [comment]
> I noticed this again too and played around with adding request headers to see what they might be detecting this time, but couldn't find anything obvious. I can't even reproduce the 401/denied response outside of the searxng request... doing a straight `curl` of the request that searxng sends with identical headers and payload comes back with a 200. Maybe they're detecting based on some quirk in the way that the python library is building the request.

Was playing with the requests and headers with Postman as well. (i even reproduced the cockie settings) I cannot reproduce the 401 with anything but SearXNG eventhough it is the same external IP. (Browsers are also not affected)
Is the request library adding any additional headers?

**Comment by dalf** [comment]
> Is the request library adding any additional headers?

The additional header is the Firefox User-Agent header.

* https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/search/processors/online.py#L57-L61
* https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/utils.py#L72-L77
* https://github.com/searxng/searxng/blob/master/searx/data/useragents.json

**Comment by return42** [comment]
And a Accept-Language header / see [send_accept_language_header](https://docs.searxng.org/admin/engines/settings.html#engine-settings)

https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/engines/duckduckgo.py#L34

**Comment by Error00101** [comment]
> And a Accept-Language header / see [send_accept_language_header](https://docs.searxng.org/admin/engines/settings.html#engine-settings)
> 
> https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/engines/duckduckgo.py#L34


> > Is the request library adding any additional headers?
> 
> The additional header is the Firefox User-Agent header.
> 
>     * https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/search/processors/online.py#L57-L61
> 
>     * https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/utils.py#L72-L77
> 
>     * https://github.com/searxng/searxng/blob/master/searx/data/useragents.json

I did not mean what headers searx is defining (i have read through those)! - I did mean if the lib which does do the reqest (i think it was httpx) does add anything.

Long story short:
I redirected the trafic which was meant for DDG to a tool of mine to inspect what is sent and replicated it 1:1
Still Postman does recieve the replies:

```

----------------POSTMAN (reply recieved)
BODY="q=SEARXNG&kl=de-de&df="
HEADERS = {
  'host': '0763-212-241-100-177.ngrok.io',
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0',
  'content-length': '22',
  'accept': '*/*',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'de',
  'content-type': 'application/x-www-form-urlencoded',
  'cookie': 'kl=de-de',
  'referer': 'https://lite.duckduckgo.com/',
}

----------------SEARXNG (401 ERROR)
BODY="q=SEARXNG&kl=de-de&df="
HEADERS = {
  'host': '0763-212-241-100-177.ngrok.io',
  'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0',
  'content-length': '22',
  'accept': '*/*',
  'accept-encoding': 'gzip, deflate, br',
  'accept-language': 'de',
  'content-type': 'application/x-www-form-urlencoded',
  'cookie': 'kl=de-de',
  'referer': 'https://lite.duckduckgo.com/',
}
```
Please Ignore the ngrok host header -> i used ngrok to confirm if i can replicate it

**Comment by aleksasiriski** [comment]
Is that on the same PC with Searxng and Postman?

**Comment by Error00101** [comment]
> Is that on the same PC with Searxng and Postman?

Jep it is.

**Comment by gsownsby** [comment]
Is it possible to put in a temporary "fix" that could just remove DuckDuckGo from the search engines queried?  Seeing an error message does not instill confidence in any user.  Perhaps it's not that simple but surely something could be devised.  Thanks.

**Comment by Bandit** [comment]
> Is it possible to put in a temporary "fix" that could just remove DuckDuckGo from the search engines queried? Seeing an error message does not instill confidence in any user. Perhaps it's not that simple but surely something could be devised. Thanks.

Just uncheck DDG from your Settings page...

**Comment by aleksasiriski** [comment]
> Is it possible to put in a temporary "fix" that could just remove DuckDuckGo from the search engines queried? Seeing an error message does not instill confidence in any user. Perhaps it's not that simple but surely something could be devised. Thanks.

```yaml
use_default_settings:
      engines:
        remove:
          - duckduckgo
          - duckduckgo images
```

**Comment by nicfab** [comment]
I have disabled DDG waiting for a solution, hoping soon.

```
engines:
  - name: duckduckgo
    disabled: true

  - name: duckduckgo images
    disabled: true

```

**Comment by ahmad-alkadri** [comment]
I think I found a possible solution.

Originally I thought it was DuckDuckGo specifically blocking Searx and/or SearxNG, but as mentioned above, User-Agent header is also very suspect. So I experimented by replacing the content of `searx/data/useragents.json` to:

```json
{
    "ua": [
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:101.0) Gecko/20100101 Firefox/101.0",
        "Mozilla/5.0 (Windows NT 10.0; U; Win64; x64; rv:99.0) Gecko/20100101 Firefox/99.0",
        "Mozilla/5.0 (Windows NT 10.0; U; WOW64; rv:77.0) Gecko/20100101 Firefox/77.0",
        "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.10; rv:75.0) Gecko/20100101 Firefox/75.0",
        "Mozilla/5.0 (X11; Linux; U; rv:74.0) Gecko/20100101 Firefox/74.0"
    ]
}
```

which is basically just a list of user-agents for firefox that I copy-pasted from UserAgentString.com, and then modifying the function  `gen_useragent()`, defined in [searxng/searx/utils.py](https://github.com/searxng/searxng/blob/d9ab83642f3b398c36f808bd8b08dc3b482722f4/searx/utils.py#L72-L77)` , that @dalf mentioned above into:

```python
def gen_useragent() -> str:
    """Return a random firefox browser User Agent
    """
    return choice(USER_AGENTS['ua'])
```

---

## Results

I can now search using DDG again:

![screenshot-127 0 0 1_8888-2023 02 03-00_16_12](https://user-images.githubusercontent.com/22837764/216473913-32ed0984-d562-4575-ace6-86724c219309.png)

![screenshot-127 0 0 1_8888-2023 02 03-00_18_46](https://user-images.githubusercontent.com/22837764/216473946-3e0ecb94-4c79-4e65-a2f1-50219a06c76f.png)

I also tested using the other search engines, and it seems to work well too:

![screenshot-127 0 0 1_8888-2023 02 03-00_20_17](https://user-images.githubusercontent.com/22837764/216474018-0c7dd1ae-36b5-463e-a87f-5880c92fc76d.png)

![screenshot-127 0 0 1_8888-2023 02 03-00_15_49](https://user-images.githubusercontent.com/22837764/216474029-0cd090c7-f1f1-4fe6-a2bf-8c486c5e3d7c.png)

---

There are many possible reasons on why this works and the previous implementation keeps getting blocked, but I think it's because either:
+ there's some kind of mismatch between either the versions, OS name, or gecko/webkit name, or something else
+ DDG (and maybe other engines) have looked at all the possible combinations of OSes, versions, and geckotrail from `searx/data/useragents.json` and made a kind of blocker against those
+ something unknown

---

What do you guys think? I can make a draft PR and continue testing with this.

**EDIT:** another possible solution is by using `fake-useragent` to return random user agent every time the `gen_useragent()` is called, though I haven't tested it yet.

**Comment by AlyoshaVasilieva** [comment]
I'll note here that another search engine, StartPage, issues captchas (blocks) if your User-Agent changes repeatedly (they state this on the captcha page). So while increased UA randomization might fix DDG it also might break StartPage

edit: I have removed all UA randomization from my instance, using only `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0`, and DDG is working so far

**Comment by nicfab** [comment]
> I'll note here that another search engine, StartPage, issues captchas (blocks) if your User-Agent changes repeatedly (they state this on the captcha page). So while increased UA randomization might fix DDG it also might break StartPage
> 
> edit: I have removed all UA randomization from my instance, using only `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0`, and DDG is working so far

Yes, it happened to me too.
See [#2146](https://github.com/searxng/searxng/issues/2146) and [#2152](https://github.com/searxng/searxng/issues/2152).

**Comment by return42** [comment]
See https://github.com/searxng/searxng/pull/2161 .. I have not had much time to test ... I need a few testers to confirm that the patch works / thanks :+1:

**Comment by ahmad-alkadri** [comment]
> See #2161 .. I have not had much time to test ... I need a few testers to confirm that the patch works / thanks 👍

Will test it during the day; I'll keep you updated. Thanks.

**Comment by jrester** [comment]
@return42 deployed your patch on my instance and duckduckgo is working again

**Comment by return42** [comment]
> deployed your patch on my instance and duckduckgo is working again

@jrester @ahmad-alkadri thanks for testing the patch / merged to master :+1:

**Comment by HerbCSO** [comment]
Confirmed working for me as well with the latest patch - thank you so much, awesome work! ;]

**Comment by return42** [comment]
>  awesome work! ;]

hm .. its blocked again in my instance .. I think we have to dig much deeper.

**Comment by HerbCSO** [comment]
Weird - currently still working for me. Something very odd is happening here! ;]

Let me know if you want me to do something to help with debugging.

**Comment by nicfab** [comment]
My instance is working fine after today's update.

**Comment by SailReal** [comment]
My instance is working fine after today's update too.

**Comment by Error00101** [comment]
@return42 instance is working with your patch (just updated my instance) thank you.

**Comment by return42** [comment]
My instance is well know by so many bots passing the limiter .. wait a while and report if your instances are blocked by ddg again / thanks!

**Comment by HerbCSO** [comment]
FWIW even though mine is public, I haven't advertised it anywhere, or submitted it to crawlers or anything, so at least thus far it's pretty low volume (and I hope it stays that way because I don't want a giant amount of traffic on it - it's really just for me personally ;] ). So maybe that's why I'm still OK for now. I'll keep an eye on it though and will report back if that changes.

**Comment by gsownsby** [comment]
So if this is a fix/patch for the problem, can someone distill the "how to's" in simple steps for us newbies to SearXNG?  Thanks.

**Comment by aleksasiriski** [comment]
> So if this is a fix/patch for the problem, can someone distill the "how to's" in simple steps for us newbies to SearXNG? Thanks.

Use the latest tagged official image. Simple as that

**Comment by jordemort** [comment]
Fixed on my instance w/ the latest image

**Comment by gsownsby** [comment]
For us newbies...are the Docker Hub image and the GitHub image the same?

**Comment by aleksasiriski** [comment]
> For us newbies...are the Docker Hub image and the GitHub image the same?

Probably yes, I use ghcr.io

**Comment by gsownsby** [comment]
Thank you.  The reason I ask, is that I downloaded the latest Docker image from Docker Hub (about 1 day old) and it did not solve the problem.  Which makes me think something is not up-to-date.

**Comment by return42** [comment]
@gsownsby sorry, but the docker discussion is OT in this thread.  You can ask your questions at searxng-docker or even better discuss with the community at matrix https://app.element.io/#/room/#searxng:matrix.org

> hm .. its blocked again in my instance .. I think we have to dig much deeper.

The issue I see on my instance is not related to this ticket.

I close this issue ticket / the issue is solved by

- https://github.com/searxng/searxng/pull/2161

**Comment by AgentCasey** [comment]
I got clues from reading the comments on this issue. It seems that the message goes away if the user chooses "Default language," as the "Search language." Why this stops that error, I do not know currently, only that it does, at least it solved the problem for me and I received all my clues from some of the comments supplied, so thank you all. To think that a solution would be that simple, is reason enough for viewing obstacles, from as many possible angles as one can. I'm glad I don't have to see those errors any longer and good luck. 

![example01](https://user-images.githubusercontent.com/59723952/227748000-fe57927c-4a6c-46d9-ad1d-00d0e653e83f.png)

![example00](https://user-images.githubusercontent.com/59723952/227748007-05aef8b4-e1bc-4e0c-950f-faf0836e775f.png)
