### ISSUE TITLE
SearXNG cannot add  as search engine in Firefox

### ISSUE THREAD

**Issue by wordpure** [searxng/searxng#3227]
Firefox gets an error when adding SearXNG as a search engine through the address bar.

![图片](https://github.com/searxng/searxng/assets/68013962/18aeafb1-c10f-4e6a-af39-95e15c3d9cc5)

SearXNG instance: baresearch.org
SearXNG version：2024.2.18+76845ea42
Firefox version: 123.0b9

This problem also occurs on multiple instances such as priv.au, searx.aleteoryx.me, etc.

**Comment by return42** [comment]
> Firefox version: 123.0b9

is a beta version / not an official release. Can you test with one of --> https://www.mozilla.org/en-US/firefox/releases/

**Comment by wordpure** [comment]
Thank you for your reminder.

I downloaded Firefox 122.0.1 for testing and found that SearXNG can be added from the address bar normally. On 123.0b9, even if I create a new blank configuration file, it cannot be added normally.

It seems that relevant changes have been made in the Firefox Developer Edition.

**Comment by return42** [comment]
> It seems that relevant changes have been made in the Firefox Developer Edition.

I close this issue .. we will see if release of FF-123 will have this error ..

**Comment by wordpure** [comment]
The official version of Firefox has been updated to [123.0](https://www.mozilla.org/en-US/firefox/123.0/releasenotes/), and the problem still exists.

But this version can add [Startpage](https://www.startpage.com/) normally. Maybe the problem is related to the definition of OpenSearch file?

**Comment by ghost** [comment]
yes this still exists
I have this problem : Firefox could not download the search plugin from: **_https://searx.be/opensearch.xml?method=POST&autocomplete=google&theme=simple_**
search engine : searx.be

**Comment by return42** [comment]
Can confirm Firefox 123 has an issue with the opensearch.xml file from SearXNG .. I tested other pages like wikipeda and these pages are not affected by this issue --> seems an SearXNG issue.

![image](https://github.com/searxng/searxng/assets/554536/4c912d7b-6067-4641-bff6-a8d8f7355d32)

    $ curl 'http://127.0.0.1:8888/opensearch.xml' 

### HTTP POST

```xml
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>SearXNG</ShortName>
  <LongName>SearXNG metasearch</LongName>
  <Description>SearXNG is a metasearch engine that respects your privacy.</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image type="image/png">http://127.0.0.1:8888/static/themes/simple/img/favicon.png</Image>
  <Url method="POST" rel="results" template="http://127.0.0.1:8888/search" type="text/html">
    <Param name="q" value="{searchTerms}"/>
  </Url>
  <Url method="POST" rel="suggestions" template="http://127.0.0.1:8888/autocompleter?q={searchTerms}" type="application/x-suggestions+json"/>
  <Url method="POST" rel="self" template="/opensearch.xml?method=POST&amp;autocomplete=google" type="application/opensearchdescription+xml"/>
  <Query role="example" searchTerms="SearXNG"/>
  <moz:SearchForm>http://127.0.0.1:8888/search</moz:SearchForm>
</OpenSearchDescription>
```

### HTTP GET

```xml
<?xml version="1.0" encoding="utf-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>SearXNG</ShortName>
  <LongName>SearXNG metasearch</LongName>
  <Description>SearXNG is a metasearch engine that respects your privacy.</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image type="image/png">http://127.0.0.1:8888/static/themes/simple/img/favicon.png</Image>
  <Url method="GET" rel="results" template="http://127.0.0.1:8888/search?q={searchTerms}" type="text/html"/>
  <Url method="GET" rel="suggestions" template="http://127.0.0.1:8888/autocompleter?q={searchTerms}" type="application/x-suggestions+json"/>
  <Url method="GET" rel="self" template="/opensearch.xml?method=GET&amp;autocomplete=google" type="application/opensearchdescription+xml"/>
  <Query role="example" searchTerms="SearXNG"/>
  <moz:SearchForm>http://127.0.0.1:8888/search</moz:SearchForm>
</OpenSearchDescription>
```

To compare .. here the XML from wikipedia.de

    curl 'https://de.wikipedia.org/w/opensearch_desc.php' | xml_pp 

```xml
<?xml version="1.0"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
  <ShortName>Wikipedia (de)</ShortName>
  <Description>Wikipedia (de)</Description>
  <Image height="16" type="image/x-icon" width="16">https://de.wikipedia.org/static/favicon/wikipedia.ico</Image>
  <Url method="get" template="https://de.wikipedia.org/w/index.php?title=Spezial:Suche&amp;search={searchTerms}" type="text/html"/>
  <Url method="get" template="https://de.wikipedia.org/w/api.php?action=opensearch&amp;search={searchTerms}&amp;namespace=0" type="application/x-suggestions+json"/>
  <Url method="get" template="https://de.wikipedia.org/w/api.php?action=opensearch&amp;format=xml&amp;search={searchTerms}&amp;namespace=0" type="application/x-suggestions+xml"/>
  <moz:SearchForm>https://de.wikipedia.org/wiki/Spezial:Suche</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by return42** [comment]
Dear follower of this thread, can you please test my PR https://github.com/searxng/searxng/pull/3237 .. thanks :+1:

**Comment by mstcl** [comment]
I've tested with Firefox 123.0 and SearXNG on [e8bd6c0](https://github.com/searxng/searxng/commit/e8bd6c03bf3d99d0ec5b87e5028d77a106fb01b2).

Instead of getting an error like before, I'm not getting the option to add the search engine to Firefox anymore.

![2024-02-25_16-30](https://github.com/searxng/searxng/assets/33115327/c98bec13-78f2-4852-860b-9d79929f9753)

The opensearch.xml looks correct anyway. At the moment the workaround is to set `browser.urlbar.update2.engineAliasRefresh` to `true` in `about:config` and then adding the engine manually.

**Comment by return42** [comment]
> I've tested with Firefox 123.0 and SearXNG on [e8bd6c0](https://github.com/searxng/searxng/commit/e8bd6c03bf3d99d0ec5b87e5028d77a106fb01b2).

Argh .. sorry I accidentally droped the URL needed for autodiscovery of Opensearch.

I fixed it in 

- https://github.com/searxng/searxng/pull/3245

**Comment by return42** [comment]
@mstcl PR is merged .. you can test it by example on my instance --> https://darmarit.org/searx/

**Comment by theonearon** [comment]
@return42 If possible, please do let me know if these changes are also reflective to searxng-docker or if there will be a seperate update for that. I've just set up a fresh instance 5 minutes ago and the issue still persists there. thanks a bunch!

**Comment by dalf** [comment]
@TheRealAjay most of the time, there is a delay of few minutes between the commit and the update of the docker image (automatically updated by a GitHub workflow with cache). However the delay is about 1 hour when the dependencies are updated (because of the cross compilations for the ARM architectures).

See https://hub.docker.com/r/searxng/searxng/tags : GitHub pushed the tag `2024.2.25-c0b97c654` 5 minutes after the commit c0b97c65438be44dd5f5e64786576763993ce424 on GitHub.

**Comment by ghost** [comment]
> @mstcl PR is merged .. you can test it by example on my instance --> https://darmarit.org/searx/

I tested in firefox 123.0 and it works,all done, Nice Job Guys :D

**Comment by pizzav-xyz** [comment]
sorry for the necropost but @return42 why it work on your website but not searxng.brihx.fr

**Comment by return42** [comment]
@kittenvr I can't reproduce your issue, but take in mind; you can't add two search engines with the same Name to Firefox .. and most SearXNG instances have the same name `SearXNG` / I renamed my instance to `SearXNG@darmarIT`..

![Image](https://github.com/user-attachments/assets/341a305f-c0f1-4908-9588-6089a3994acb)
