### ISSUE TITLE
Had to use latest msgspec (Python 3.12 to Python 3.13 upgrade)

### ISSUE THREAD

**Issue by bojanstef** [searxng/searxng#4015]
Update from the SearXNG maintainers (20241229): if you have issues with the upgrade of the CPython (Python 3.12 to Python 3.13 upgrade), please read https://github.com/searxng/searxng/issues/4015#issuecomment-2564670601 first.

---

Using the latest commit (https://github.com/bojanstef/searxng/commit/abd9b271bc1c4cc4dc1ee531944ce27c1e2734cc) from my fork: https://github.com/bojanstef/searxng when I run the following command from the documentation here https://docs.searxng.org/admin/installation-docker.html#build-the-image
```shell
make docker.build
``` 

<details>
<summary>I get this failing output (click to expand)</summary>

```shell
Building wheels for collected packages: msgspec
  Building wheel for msgspec (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for msgspec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [51 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/msgpack.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/_version.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/__init__.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/yaml.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/structs.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/inspect.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/_json_schema.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/json.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/_utils.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/toml.py -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/msgpack.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/__init__.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/json.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/structs.pyi -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      copying msgspec/py.typed -> build/lib.macosx-14.0-arm64-cpython-313/msgspec
      UPDATING build/lib.macosx-14.0-arm64-cpython-313/msgspec/_version.py
      set build/lib.macosx-14.0-arm64-cpython-313/msgspec/_version.py to '0.18.6'
      running build_ext
      building 'msgspec._core' extension
      creating build/temp.macosx-14.0-arm64-cpython-313/msgspec
      clang -fno-strict-overflow -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk -I/opt/homebrew/opt/openjdk@17/include -I/Users/bojanstef/Developer/searxng/local/py3/include -I/opt/homebrew/opt/python@3.13/Frameworks/Py
thon.framework/Versions/3.13/include/python3.13 -c msgspec/_core.c -o build/temp.macosx-14.0-arm64-cpython-313/msgspec/_core.o
      msgspec/_core.c:500:13: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
              if (_PyUnicode_EQ(kwname, key)) {
                  ^
      msgspec/_core.c:4452:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          while (_PySet_NextEntry(state->structs_set, &set_pos, &set_item, &set_hash)) {
                 ^
      msgspec/_core.c:7316:17: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  if (_PyUnicode_EQ(kwname, field)) {
                      ^
      msgspec/_core.c:7723:17: error: call to undeclared function '_PyUnicode_EQ'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  if (_PyUnicode_EQ(kwname, field)) goto kw_found;
                      ^
      msgspec/_core.c:11254:72: error: too few arguments to function call, expected 6, have 5
          int out = _PyLong_AsByteArray((PyLongObject *)int128, buf, 16, 0, 0);
                    ~~~~~~~~~~~~~~~~~~~                                      ^
      /opt/homebrew/opt/python@3.13/Frameworks/Python.framework/Versions/3.13/include/python3.13/cpython/longobject.h:111:17: note: '_PyLong_AsByteArray' declared here
      PyAPI_FUNC(int) _PyLong_AsByteArray(PyLongObject* v,
                      ^
      msgspec/_core.c:12426:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          while (_PySet_NextEntry(obj, &ppos, &item, &hash)) {
                 ^
      msgspec/_core.c:13748:12: error: call to undeclared function '_PySet_NextEntry'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
          while (_PySet_NextEntry(obj, &ppos, &item, &hash)) {
                 ^
      7 errors generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for msgspec
Failed to build msgspec
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (msgspec)
ERROR: ./manage: line 307: error while pip install (local/py3/bin)
make: *** [docker.build] Error 42
```

</details>

Searching, I found this related issue: https://github.com/jcrist/msgspec/issues/698#issuecomment-2428026677 and changing the requirements.txt file fixed the problem for me:
```diff
certifi==2024.8.30
babel==2.16.0
flask-babel==4.0.0
flask==3.0.3
jinja2==3.1.4
lxml==5.3.0
pygments==2.18.0
python-dateutil==2.9.0.post0
pyyaml==6.0.2
httpx[http2]==0.24.1
Brotli==1.1.0
uvloop==0.21.0
httpx-socks[asyncio]==0.7.7
setproctitle==1.3.3
redis==5.0.8
markdown-it-py==3.0.0
fasttext-predict==0.9.2.2
tomli==2.0.2; python_version < '3.11'
-msgspec==0.18.6
+msgspec @ git+https://github.com/jcrist/msgspec.git@main#egg=msgspec
eval_type_backport; python_version < '3.9'
typer-slim==0.13.0
```

**Comment by return42** [comment]
@bojanstef thanks a lot for pointing out, but except waiting for the next release, IDK what else we can do when msgspec does not compile in Python 3.13 on macOS.

**Comment by bojanstef** [comment]
@return42 yup, I figured it would be good to post a workaround anyways in case other people run into the same issue.

**Comment by return42** [comment]
>  figured it would be good to post a workaround anyways in case other people run into the same issue.

Yeah, thanks a lot .. sadly we can not publish on pypi with a requirement from ``git+https://github.com/jcrist/msgspec.git@main#egg=msgspec`` :-)

I opened a PR for Python 3.13 support:

-  #4036

**Comment by Popolon** [comment]
Arch Linux now uses Python 3.13 as Python,  so searx can't be installed on it now.

**Comment by return42** [comment]
Thats a pity / https://github.com/jcrist/msgspec/issues/764#issuecomment-2561330165 

I will give [`msgspec-python313-pre`](https://github.com/jcrist/msgspec/issues/764#issuecomment-2466150924) a try ..

**Comment by return42** [comment]
@Popolon I merged:

- https://github.com/searxng/searxng/pull/4129

> Arch Linux now uses Python 3.13 as Python, so searx can't be installed on it now.

Update SearXNG clone and it should now work again.

**Comment by Popolon** [comment]
It didn't work either, because some dependencies missed not wrote in the install documentation (and it don't work anymore on python 3.11 (as debian bookworm) or python 3.12 (as ubuntu noble), that I tried in LXC containers.
The solution I found for Arch  with 3.13  (should maybe be added to doc or dependencies):

```
pip install pdm
pip install pdm.backend
```

still block here, it uninstall httpx, and then say that ``unearth 0.17.2 requires httpx<1,>=0.27``:
<pre>
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unearth 0.17.2 requires httpx<1,>=0.27.0, but you have httpx 0.24.1 which is incompatible.
pdm 2.22.1 requires httpcore>=1.0.6, but you have httpcore 0.17.3 which is incompatible.
Successfully installed Brotli-1.1.0 MarkupSafe-3.0.2 Werkzeug-3.1.3 async-timeout-5.0.1 babel-2.16.0 click-8.1.8 fasttext-predict-0.9.2.4 flask-3.1.0 flask-babel-4.0.0 h2-4.1.0 hpack-4.0.0 httpcore-0.17.3 httpx-0.24.1 httpx-socks-0.7.7 hyperframe-6.0.1 isodate-0.7.2 itsdangerous-2.2.0 jinja2-3.1.4 lxml-5.3.0 msgspec-python313-pre-0.19.3 python-dateutil-2.9.0.post0 python-socks-2.5.3 pytz-2024.2 redis-5.0.8 searxng-2024.12.24+374915466 setproctitle-1.3.4 six-1.17.0 typer-slim-0.15.1 typing-extensions-4.12.2 uvloop-0.21.0
</pre>

**Comment by return42** [comment]
> python 3.11 (as debian bookworm) or python 3.12 (as ubuntu noble), that I tried in LXC containers.
The solution I found for Arch with 3.13 (should maybe be added to doc or dependencies):

Sure? .. a fresh install? .. in the CI tests from https://github.com/searxng/searxng/pull/4036 everything passed the tests ``python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]``.

**Comment by Popolon** [comment]
It worked today, after a new git pull on last arch, python 3.13, that was not the case 2 days ago, and where I installed manually pdm. Thanks for your work :).


Still don't work anymore on Ubuntu 22.04, python 3.10. (with still missing pdm dependency, added it manually). I used in both case this documentation: https://docs.searxng.org/admin/installation-searxng.html#installation-basic

<pre>
  Attempting uninstall: httpx
    Found existing installation: httpx 0.24.1
    Uninstalling httpx-0.24.1:
      Successfully uninstalled httpx-0.24.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
httpx-socks 0.7.7 requires httpcore<0.18.0,>=0.17.3, but you have httpcore 1.0.7 which is incompatible.
httpx-socks 0.7.7 requires httpx<0.25.0,>=0.21.0, but you have httpx 0.28.1 which is incompatible.
searxng 2024.12.22+26097f444 requires httpx[http2]==0.24.1, but you have httpx 0.28.1 which is incompatible.
</pre>

**Comment by rob4226** [comment]
I got the same errors with Python 3.11.  First it failed saying I didn't have `pdm` and `pdm.backend` so I installed those, but then I got the pip dependency resolver error due to version conflicts with `httpx`.

I switched to commit 26097f444b536e07f4790597134ab20df5639df3 and then it worked fine.

**Comment by return42** [comment]
> It worked today, after a new git pull on last arch, python 3.13, that was not the case 2 days ago, and where I installed manually pdm. Thanks for your work :).

Don't install any additional packages into the virtual env of the SearXNG installation.

> I switched to commit https://github.com/searxng/searxng/commit/26097f444b536e07f4790597134ab20df5639df3 and then it worked fine.

This does not mean its related to SearXNG; when you install pdm you have new requirements in the requirements-chain of the virtual env causing such trouble.

Reinstall from scratch or at least drop the virtual-env and build up a new one.

To be clear: pdm is not a requirement of SearXNG nor a sub-sub-requirement / pdm is not in the requirements-chain of SearXNG.

**Comment by rob4226** [comment]
> > I switched to commit [26097f4](https://github.com/searxng/searxng/commit/26097f444b536e07f4790597134ab20df5639df3) and then it worked fine.
> 
> This does not mean its related to SearXNG; when you install pdm you have new requirements in the requirements-chain of the virtual env causing such trouble.
> 
> Reinstall from scratch or at least drop the virtual-env and build up a new one.
> 
> To be clear: pdm is not a requirement of SearXNG nor a sub-sub-requirement / pdm is not in the requirements-chain of SearXNG.

It may not be a requirement of SearXNG but it's getting pulled in somehow as multiple people have reported (https://github.com/searxng/searxng/discussions/4137 https://github.com/searxng/searxng/issues/4015#issuecomment-2561445660).  To be clear, I did not want to install `pdm` (nor did anyone else), I only did because the install of SearXNG failed with error `ModuleNotFoundError: No module named 'pdm'`.  This happened on two different O/S's Ubuntu 20.04 and FreeBSD 14.2 using Python 3.11.  Following the [step-by-step docs](https://docs.searxng.org/admin/installation-searxng.html#installation-basic) I can replicate the error:

```sh
# Ubuntu 20.04.6 LTS
cd /tmp
mkdir /tmp/searxng
git clone git@github.com:searxng/searxng.git searxng/searxng-src
cd searxng/searxng-src/
# Switch to commit as of last night:
git switch -d 73e395c8ceecf015e1fa3c56b8c8e09780472604
cd ..
python3.11 -m venv venv311
source ./venv311/bin/activate
command -v python && python --version
# /tmp/searxng/venv311/bin/python
# Python 3.11.10
pip -VV
# pip 24.3.1 from /tmp/searxng/venv311/lib/python3.11/site-packages/pip (python 3.11)
pip install -U pip
pip install -U setuptools
pip install -U wheel
pip install -U pyyaml
cd searxng-src
pip install --use-pep517 --no-build-isolation -e .
```

```log
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 527, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 642, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 72, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 69, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 575, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 722, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 321, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pyproject_hooks._impl.BackendUnavailable: Traceback (most recent call last):
  File "/tmp/searxng/venv311/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pdm'
```

The good news is that if you follow the same set of instructions using this morning's commits it works! (just remove the line `git switch -d 73e395c8ceecf015e1fa3c56b8c8e09780472604` from above to use latest commit on master) So whatever was done this morning fixed it!

**Comment by return42** [comment]
> To be clear, I did not want to install `pdm` (nor did anyone else), I only did because the install of SearXNG failed with error `ModuleNotFoundError: No module named 'pdm'`
...
> So whatever was done this morning fixed it!

Ah, OK thanks a lot for pointing out :+1: .. then I guess pdm requirement was from the [interim package](https://github.com/jcrist/msgspec/issues/764#issuecomment-2564339495) we added in  https://github.com/searxng/searxng/pull/4129 and removed this morning in PR https://github.com/searxng/searxng/pull/4142

Sorry, but the late support of msgspec for python 3.13, which was only available this morning, seems to have caused some confusion .. I hope msgspec won't do the same game again in the future when py3.14 is released ;-)

**Comment by return42** [comment]
For those coming around and having issues with Python 3.13 upgrades:

If you have a Linux distribution with rolling releases like ArchLinux and the distribution upgrades the CPython version from e.g. Python 3.12 to Python 3.13 (like ArchLinux did the last days), **then you have to rebuild the virtual environment of the SearXNG installation!!!**

If you had used the installation scripts for the SearXNG installation, then you can rebuild a fresh virtualenv easily by:

    sudo -H ./utils/searxng.sh remove pyenv
    sudo -H ./utils/searxng.sh install pyenv
 
Otherwise you will see issues like:

```
sudo -H ./utils/searxng.sh instance update
...
pip install -U pip
  |searxng| Traceback (most recent call last):
  |searxng|   File "/usr/local/searxng/searx-pyenv/bin/pip", line 5, in <module>
  |searxng|     from pip._internal.cli.main import main
  |searxng| ModuleNotFoundError: No module named 'pip'
```

**Comment by rob-sve** [comment]
I had to downgrade my python-httpx package on Arch Linux from `0.28.1` to `0.27.2` to get SearXNG running again after a system upgrade. I'm using the aur pkgbuild to install SearxNG btw.

With `0.28.1` I was getting errors like these:
```
2024-12-29 22:33:54,277 ERROR:searx.engines.soundcloud: Fail to initialize
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/searx/search/processors/abstract.py", line 73, in initialize
    self.engine.init(get_engine_from_settings(self.engine_name))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/searx/engines/soundcloud.py", line 69, in init
    guest_client_id = get_client_id()
  File "/usr/lib/python3.13/site-packages/searx/engines/soundcloud.py", line 45, in get_client_id
    resp = http_get("https://soundcloud.com")
  File "/usr/lib/python3.13/site-packages/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python3.13/site-packages/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.13/site-packages/searx/network/network.py", line 291, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/searx/network/network.py", line 267, in call_client
    client = await self.get_client(**kwargs_clients)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/searx/network/network.py", line 188, in get_client
    client = new_client(
        self.enable_http,
    ...<9 lines>...
        hook_log_response,
    )
  File "/usr/lib/python3.13/site-packages/searx/network/client.py", line 187, in new_client
    transport = get_transport(verify, enable_http2, local_address, None, limit, retries)
  File "/usr/lib/python3.13/site-packages/searx/network/client.py", line 141, in get_transport
    verify = get_sslcontexts(None, None, verify, True, http2) if verify is True else verify
             ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/searx/network/client.py", line 53, in get_sslcontexts
    SSLCONTEXTS[key] = httpx.create_ssl_context(cert, verify, trust_env, http2)
                       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: create_ssl_context() takes from 0 to 3 positional arguments but 4 were given
```

I understand it's not compatible. Just posting for others looking for solutions.

**Comment by return42** [comment]
> I had to downgrade my python-httpx package on Arch Linux from `0.28.1` to `0.27.2` 
> ..
> I'm using the aur pkgbuild to install SearxNG btw.

Please report this issue to the package manager at ArchLinux / ping @HLFH

**Comment by Popolon** [comment]
@return42, I managed to install version compatible python 3.13, last week, on Arch, by not using the Arch package, but following the guide, here https://docs.searxng.org/admin/installation-searxng.html#installation-basic (just need to add pdm and another pdm related package (you will see at the end of the error output during installation).

**Comment by HLFH** [comment]
@rob-sve @Popolon @rob4226
And AUR users @stef204 @morsmortium @liquidsky @DanSman @sen @krs @zynex @flylightning @backd00r @AlexBocken

The Arch Linux AUR [`searxng-git`](https://aur.archlinux.org/packages/searxng-git) package has been fixed and upgraded.
The requirements from `requirements.txt` are now perfectly matched.
`searxng-git` now uses a python virtual environment which is the best Arch Linux setup for python packages.
