### ISSUE TITLE
Unit converter crashes

### ISSUE THREAD

**Issue by IGLADI** [searxng/searxng#4461]
**Version of SearXNG, commit number if you are using on master branch and stipulate if you forked SearXNG**
2025.3.7+67a8b66f7

**How did you install SearXNG?**
docker.io/searxng/searxng:latest

**What happened?**
I activated the unit converter plugin for the first time today and it seems to simply not work at all, check the log section for the full traceback.
I also tried using public instances with the public and don't get any unit conversion so I'm guessing it's a bug everyone has.

**How To Reproduce**
I just enabled the plugin and searched for "5m to cm" or basically anything else.

**Expected behavior**
Getting the unit conversion result I asked for.

**Screenshots & Logs**
![Image](https://github.com/user-attachments/assets/1b69236e-df33-4965-9839-369dd49b6843)
```2025-03-07 16:09:20,695 ERROR:unit_converter: Exception while calling post_search
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/_core.py", line 421, in post_search
    results = plugin.post_search(request=request, search=search) or []
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/_core.py", line 238, in post_search
    return self.module.post_search(request, search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/unit_converter.py", line 267, in post_search
    Answer(results=results, answer=target_val)
TypeError: Unexpected keyword argument 'results'
2025-03-07 16:10:49,993 ERROR:unit_converter: Exception while calling post_search
Traceback (most recent call last):
  File "/usr/local/searxng/searx/plugins/_core.py", line 421, in post_search
    results = plugin.post_search(request=request, search=search) or []
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/_core.py", line 238, in post_search
    return self.module.post_search(request, search)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/plugins/unit_converter.py", line 267, in post_search
    Answer(results=results, answer=target_val)
TypeError: Unexpected keyword argument 'results'```

**Comment by return42** [comment]
Thanks for bug report .. I fixed the issue in:

- https://github.com/searxng/searxng/pull/4424

Can you please test the PR .. thanks 👍

**Comment by IGLADI** [comment]
> Thanks for bug report .. I fixed the issue in:
> 
> * [[refactor] typification of SearXNG (MainResult) / result items (part 2) #4424](https://github.com/searxng/searxng/pull/4424)
> 
> Can you please test the PR .. thanks 👍

Yup this indeed fixes it, however I seem to get this:
![Image](https://github.com/user-attachments/assets/823adb9d-35d2-48a8-ad8b-7c7459371423)
which I do not get when switching back to latest tag (I tried a couple of times and it never works in your pr and always on latest, maybe your pr misses another fix from main?)
On latest I get this which I don't really mind tbh:
![Image](https://github.com/user-attachments/assets/ffcdd903-acff-4865-8490-269ede8dab2e)

**Comment by return42** [comment]
Could you give it another try ..

> maybe your pr misses another fix from main

I rebased & force pushed in the mean time, not sure what version you have tested .. the unexpected crash from ddg make me wonder (i can't reproduce) .. if you see issues again, please post the debug log .. do you have any special setup in your test scenario? / thanks 👍

**Comment by IGLADI** [comment]
Nope still the same :/

Here is the complete log, by reading it I don't seem to find the error as it seem to really receive a too many request each time by google but the latest tag it doesn't, mabye this is on the request side? Like the latest tag seems more like a real person? idk

```docker logs searxng
SearXNG version 0.4
Use existing /etc/searxng/uwsgi.ini
Use existing /etc/searxng/settings.yml
Listen on 0.0.0.0:8080
[uWSGI] getting INI configuration from /etc/searxng/uwsgi.ini
[uwsgi-static] added mapping for /static => /usr/local/searxng/searx/static
*** Starting uWSGI 2.0.23 (64bit) on [Fri Mar  7 17:35:52 2025] ***
compiled with version: 13.2.1 20231014 on 30 November 2023 14:34:33
os: Linux-5.10.160-rockchip #37 SMP Fri Apr 26 05:16:30 UTC 2024
nodename: bc32f0e14fb0
machine: aarch64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /usr/local/searxng
detected binary path: /usr/sbin/uwsgi
chdir() to /usr/local/searxng/searx/
your memory page size is 4096 bytes
detected max file descriptor number: 1048576
building mime-types dictionary from file /etc/mime.types...1390 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 0.0.0.0:8080 fd 3
Python version: 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014]
Python main interpreter initialized at 0xffffb6a6fac0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 1086048 bytes (1060 KB) for 32 cores
*** Operational MODE: preforking+threaded ***
added /usr/local/searxng/ to pythonpath.
spawned uWSGI master process (pid: 7)
spawned uWSGI worker 1 (pid: 11, cores: 4)
spawned uWSGI worker 2 (pid: 14, cores: 4)
spawned 4 offload threads for uWSGI worker 1
spawned 4 offload threads for uWSGI worker 2
spawned uWSGI worker 3 (pid: 21, cores: 4)
spawned uWSGI worker 4 (pid: 22, cores: 4)
spawned uWSGI worker 5 (pid: 25, cores: 4)
spawned 4 offload threads for uWSGI worker 3
spawned uWSGI worker 6 (pid: 31, cores: 4)
spawned 4 offload threads for uWSGI worker 5
spawned uWSGI worker 7 (pid: 36, cores: 4)
spawned 4 offload threads for uWSGI worker 4
spawned 4 offload threads for uWSGI worker 7
spawned uWSGI worker 8 (pid: 42, cores: 4)
spawned 4 offload threads for uWSGI worker 6
spawned 4 offload threads for uWSGI worker 8
2025-03-07 17:35:52,629 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,629 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,655 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,676 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,749 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,796 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,843 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:52,850 WARNING:searx: Be aware you have activated features intended only for public instances. This force the usage of the limiter and link_token / see https://docs.searxng.org/admin/searx.limiter.html
2025-03-07 17:35:53,514 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,515 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:53,529 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,529 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:53,683 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,686 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:53,721 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,722 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:53,787 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,787 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:53,852 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:53,852 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:54,278 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:54,278 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
2025-03-07 17:35:54,298 ERROR:MOA: GitPython is not installed.
2025-03-07 17:35:54,298 ERROR:MOA: Git is not installed or the directory is not a git repository, falling back to default values.
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xffffb6a6fac0 pid: 36 (default app)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xffffb6a6fac0 pid: 11 (default app)
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0xffffb6a6fac0 pid: 21 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb6a6fac0 pid: 31 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb6a6fac0 pid: 25 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb6a6fac0 pid: 22 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb6a6fac0 pid: 14 (default app)
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0xffffb6a6fac0 pid: 42 (default app)
2025-03-07 17:35:56,596 WARNING:searx.engines.ddg definitions: ErrorContext('searx/engines/duckduckgo_definitions.py', 104, "results.append({'answer': html_to_text(answer), 'url': search_res.get('AbstractURL', '')})", 'AttributeError', None, ()) False
2025-03-07 17:35:56,597 ERROR:searx.engines.ddg definitions: exception : 'dict' object has no attribute 'replace'
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 151, in _search_basic
    return self.engine.response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/engines/duckduckgo_definitions.py", line 104, in response
    results.append({'answer': html_to_text(answer), 'url': search_res.get('AbstractURL', '')})
                              ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/utils.py", line 165, in html_to_text
    html_str = html_str.replace('\n', ' ').replace('\r', ' ')
               ^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'replace'
2025-03-07 17:35:56,897 WARNING:searx.engines.google: ErrorContext('searx/search/processors/online.py', 116, "response = req(params['url'], **request_args)", 'searx.exceptions.SearxEngineTooManyRequestsException', None, ('Too many request',)) False
2025-03-07 17:35:56,897 ERROR:searx.engines.google: Too many requests
Traceback (most recent call last):
  File "/usr/local/searxng/searx/search/processors/online.py", line 163, in search
    search_results = self._search_basic(query, params)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 147, in _search_basic
    response = self._send_http_request(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/search/processors/online.py", line 116, in _send_http_request
    response = req(params['url'], **request_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 164, in get
    return request('get', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/__init__.py", line 95, in request
    return future.result(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/searxng/searx/network/network.py", line 289, in request
    return await self.call_client(False, method, url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 272, in call_client
    return Network.patch_response(response, do_raise_for_httperror)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/searxng/searx/network/network.py", line 245, in patch_response
    raise_for_httperror(response)
  File "/usr/local/searxng/searx/network/raise_for_httperror.py", line 76, in raise_for_httperror
    raise SearxEngineTooManyRequestsException()
searx.exceptions.SearxEngineTooManyRequestsException: Too many request, suspended_time=3600```

**Comment by IGLADI** [comment]
Wait wtf there seem to be a bug on my side.

When I run your local code it seem to partially use an old fork I used before (MOA) but not when I use the latest tag, give me a sec

**Comment by IGLADI** [comment]
Update: Yeah everything is fixed in your pr even the bing parsing, sorry for the confusion I still had a volume laying around in the docker compose I used for building your pr
